//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewelery
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ProdutsDetails
    {
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public byte Количество_на_складе { get; set; }
        public decimal Стоимость { get; set; }
        public byte Максимальная_скидка { get; set; }
        public byte Действующая_скидка { get; set; }
        public string Категория_товара { get; set; }
        public string Описание { get; set; }
    }
}
