//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewelery
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ProductList
    {
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public byte Единица_измерения { get; set; }
        public decimal Стоимость { get; set; }
        public byte Размер_максимально_возможной_скидки { get; set; }
        public byte Производитель { get; set; }
        public string Наименование_производителя { get; set; }
        public byte Поставщик { get; set; }
        public string Наименование_поставщика { get; set; }
        public byte Категория_товара { get; set; }
        public string Наименование_категории { get; set; }
        public byte Действующая_скидка { get; set; }
        public byte Кол_во_на_складе { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
    }
}
