//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewelery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.Состав_заказов = new HashSet<Состав_заказов>();
        }
    
        public byte Код { get; set; }
        public System.DateTime Дата_заказа { get; set; }
        public System.DateTime Дата_доставки { get; set; }
        public byte Пункт_выдачи { get; set; }
        public Nullable<byte> Код_клиента { get; set; }
        public byte Код_для_получения { get; set; }
        public byte Статус_заказа { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Пункты_выдачи Пункты_выдачи { get; set; }
        public virtual Статусы Статусы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_заказов> Состав_заказов { get; set; }
    }
}
