//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewelery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукция()
        {
            this.Состав_заказов = new HashSet<Состав_заказов>();
        }
    
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public byte Единица_измерения { get; set; }
        public decimal Стоимость { get; set; }
        public byte Размер_максимально_возможной_скидки { get; set; }
        public byte Производитель { get; set; }
        public byte Поставщик { get; set; }
        public byte Категория_товара { get; set; }
        public byte Действующая_скидка { get; set; }
        public byte Кол_во_на_складе { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
    
        public virtual Единицы_измерения Единицы_измерения { get; set; }
        public virtual Категории Категории { get; set; }
        public virtual Поставщики Поставщики { get; set; }
        public virtual Производители Производители { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_заказов> Состав_заказов { get; set; }
    }
}
